In [14]:
import numpy as np

In [15]:
minha_lista = [1, 2, 3, 4, 5]

In [16]:
minha_lista

[1, 2, 3, 4, 5]

In [17]:
np.array(minha_lista)

array([1, 2, 3, 4, 5])

In [18]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0, 10, 4)


array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [30]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.random.rand(5)

array([0.57138412, 0.71152911, 0.51767546, 0.11930824, 0.13175623])

In [32]:
np.random.rand(5) * 100


array([42.96867057, 95.97093428, 96.63718705, 52.84547523,  1.69631693])

In [33]:
np.random.rand(5, 3)


array([[0.12007186, 0.03269161, 0.27283646],
       [0.00769159, 0.61950257, 0.73398758],
       [0.65218064, 0.92476432, 0.94675042],
       [0.91810661, 0.03659877, 0.24313362],
       [0.5621116 , 0.8252969 , 0.22962774]])

In [34]:
np.random.rand(5, 3, 2)


array([[[0.9939135 , 0.38800257],
        [0.59633193, 0.24324954],
        [0.13153005, 0.89898057]],

       [[0.70870531, 0.43092016],
        [0.38222822, 0.17116066],
        [0.36182464, 0.03355946]],

       [[0.72687092, 0.40039327],
        [0.41537649, 0.83840009],
        [0.68930362, 0.53234483]],

       [[0.06149658, 0.72947203],
        [0.9221532 , 0.94201382],
        [0.26787432, 0.6301736 ]],

       [[0.97738405, 0.99348196],
        [0.80780359, 0.94994927],
        [0.95988335, 0.49901511]]])

In [35]:
np.random.randn(3)

array([1.20719463, 0.64165473, 0.32417409])

In [37]:
np.random.randint(0, 100, 12)


array([ 5, 25, 30, 99, 27, 15, 32, 14,  0, 33, 46, 64])

In [39]:
np.random.rand(12) *100

array([44.79322206, 96.08016863, 37.03444216, 13.16014985, 31.05274865,
       39.3942529 , 28.43055442,  7.13110475, 21.10035368, 87.24988596,
       55.6914636 ,  2.36030607])

In [40]:
np.round(np.random.rand(12) *100)


array([70., 80., 96., 94., 47., 88., 29., 33., 31., 78.,  4., 86.])

In [42]:
arr = np.random.rand(25)

In [43]:
arr

array([0.84534983, 0.74981079, 0.65550254, 0.72069886, 0.99386293,
       0.7516063 , 0.2873949 , 0.57131813, 0.55768011, 0.08397649,
       0.77770906, 0.48117751, 0.6667313 , 0.42931923, 0.03729572,
       0.1274239 , 0.26184707, 0.5496771 , 0.08097146, 0.7589349 ,
       0.19591325, 0.09625046, 0.83374789, 0.37159434, 0.32406053])

In [44]:
arr.reshape(5, 5)

array([[0.84534983, 0.74981079, 0.65550254, 0.72069886, 0.99386293],
       [0.7516063 , 0.2873949 , 0.57131813, 0.55768011, 0.08397649],
       [0.77770906, 0.48117751, 0.6667313 , 0.42931923, 0.03729572],
       [0.1274239 , 0.26184707, 0.5496771 , 0.08097146, 0.7589349 ],
       [0.19591325, 0.09625046, 0.83374789, 0.37159434, 0.32406053]])

In [45]:
arr

array([0.84534983, 0.74981079, 0.65550254, 0.72069886, 0.99386293,
       0.7516063 , 0.2873949 , 0.57131813, 0.55768011, 0.08397649,
       0.77770906, 0.48117751, 0.6667313 , 0.42931923, 0.03729572,
       0.1274239 , 0.26184707, 0.5496771 , 0.08097146, 0.7589349 ,
       0.19591325, 0.09625046, 0.83374789, 0.37159434, 0.32406053])

In [46]:
arr.shape

(25,)

In [47]:
arr_rshp = arr.reshape(5, 5)

In [48]:
arr_rshp

array([[0.84534983, 0.74981079, 0.65550254, 0.72069886, 0.99386293],
       [0.7516063 , 0.2873949 , 0.57131813, 0.55768011, 0.08397649],
       [0.77770906, 0.48117751, 0.6667313 , 0.42931923, 0.03729572],
       [0.1274239 , 0.26184707, 0.5496771 , 0.08097146, 0.7589349 ],
       [0.19591325, 0.09625046, 0.83374789, 0.37159434, 0.32406053]])

In [49]:
arr_rshp.shape

(5, 5)

In [53]:
print(arr_rshp.min())
print(arr_rshp.max())


0.03729572098403
0.9938629281821363


In [55]:
arr_rshp.argmax()

4

In [57]:
arr_rshp.argmin()

14

In [64]:
arr_rshp[1,4]

0.0839764918475514