In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 30, 3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[3]

9

In [6]:
arr[2:5]

array([ 6,  9, 12])

In [7]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [11]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
arr[2:] = 100

In [13]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr = np.arange(50).reshape(5, 10)

In [15]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
arr.shape

(5, 10)

In [19]:
arr2 = arr[:3]

In [20]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr2[:3] = 100

In [22]:
print(arr)
print(arr2)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]
[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [23]:
arr2 = arr.copy()

In [24]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [25]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [26]:
arr2[:3] = 1

In [27]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [28]:
arr2

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
arr2[3:,5:7]

array([[35, 36],
       [45, 46]])

In [33]:
bol = arr < 24 

In [34]:
bol

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [49]:
array = np.random.rand(5, 5) * 100

In [50]:
array

array([[12.00437504, 92.91749333, 11.44256304, 54.15128805, 26.16192048],
       [40.71501105, 78.26534921, 45.4523674 , 93.78183166, 86.6327256 ],
       [36.20776982,  7.96291806, 57.71520278, 37.92718536, 68.26500066],
       [85.12928588, 57.45090172, 88.53232376, 98.71137803,  8.30123672],
       [87.90797372, 20.48342886, 37.06164496, 94.78444163, 85.48516865]])

In [52]:
bol = array < 35

In [53]:
bol

array([[ True, False,  True, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False, False]])

In [54]:
array[bol]

array([12.00437504, 11.44256304, 26.16192048,  7.96291806,  8.30123672,
       20.48342886])